context:
  version: "20.5.3"

package:
  name: commitlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@commitlint/cli/-/cli-${{ version }}.tgz
  sha256: 60d3dcc3b9ee0251fa91a45168ba6d398aa8525b3b2a70f76b25fb99c2e78c7d

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - commitlint --help

about:
  license: MIT
  license_file:
    - license.md
    - third-party-licenses.txt
  summary: Lint commit messages according to a commit convention
  homepage: https://commitlint.js.org
  repository: https://github.com/conventional-changelog/commitlint

extra:
  recipe-maintainers:
    - danielnachun
