context:
  version: "20.3.1"

package:
  name: commitlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@commitlint/cli/-/cli-${{ version }}.tgz
  sha256: ab1d0f6a1b9edb28be794886d50f3be72991c0cb8048283dda97c0ee4dc8598a

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - commitlint --help

about:
  license: MIT
  license_file:
    - license.md
    - third-party-licenses.txt
  summary: Lint commit messages according to a commit convention
  homepage: https://commitlint.js.org
  repository: https://github.com/conventional-changelog/commitlint

extra:
  recipe-maintainers:
    - danielnachun
