context:
  version: "21.0.1"

package:
  name: commitlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@commitlint/cli/-/cli-${{ version }}.tgz
  sha256: 29d3f0c9a2241cad7e871b82892c25d76cc2574ba46ca1ea282da8ab92cdbead

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - commitlint --help

about:
  license: MIT
  license_file:
    - license.md
    - third-party-licenses.txt
  summary: Lint commit messages according to a commit convention
  homepage: https://commitlint.js.org
  repository: https://github.com/conventional-changelog/commitlint

extra:
  recipe-maintainers:
    - danielnachun
