context:
  version: "20.4.3"

package:
  name: commitlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@commitlint/cli/-/cli-${{ version }}.tgz
  sha256: 8e6f0b52d8abe6750d3372f03db2c025688481de83bcac503a1887bd1c0775de

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - commitlint --help

about:
  license: MIT
  license_file:
    - license.md
    - third-party-licenses.txt
  summary: Lint commit messages according to a commit convention
  homepage: https://commitlint.js.org
  repository: https://github.com/conventional-changelog/commitlint

extra:
  recipe-maintainers:
    - danielnachun
