context:
  version: "20.3.0"

package:
  name: commitlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@commitlint/cli/-/cli-${{ version }}.tgz
  sha256: e64cc02a2803ae3c0593904f42354dc5bdc380273eb3b69ccb99fe8ef90ef90e

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - commitlint --help

about:
  license: MIT
  license_file:
    - license.md
    - third-party-licenses.txt
  summary: Lint commit messages according to a commit convention
  homepage: https://commitlint.js.org
  repository: https://github.com/conventional-changelog/commitlint

extra:
  recipe-maintainers:
    - danielnachun
